export const churchSongs = [
{
    id: 1,
    title: 'To my knees',
    keyOf: 'C',
    songAndChords:
    `
[Intro]
 
C | F | Am G C/E | F |
 
 
[Verse 1]
 
       C
In the Saviour's love
       F
I find joy beyond compare
        Am           G   C/E  F
Endless peace covers all of   me
         C
When You breathe within
         F
You turn winter into spring
         Am            G   C/E  F
Grace dissolves every fear in   me
 
 
[Chorus]
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
 
[Instrumental]
 
C | F | Am G C/E | F |
 
 
[Verse 2]
 
      C
In my vacant heart
         F
Lord You came and made a home
          Am           G    C/E  F
You bring light to the dark in   me
       C
When I lose my way
     F
I am beckoned into grace
     Am          G   C/E    F
You alone are my e - very - thing
 
 
[Chorus] x2
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C |
 
 
[Bridge] x2
 
G                       Dm          F    C
  All the earth sing of mercy never en - ding
G                     Dm              F   C
  I will worship with all that is within me
G            Dm          F  C
  Holy holy, Lord God almighty
G                  Dm          F  C
  King of heaven, Yours is the glory
 
| G |
 
 
[Chorus]
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C |
 
 
[Instrumental] x10
 
| C  Dm | Am  G | F | C  G |
 
 
[Chorus] x2
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C

`
},
{
    id: 2,
    title: 'Oceans',
    keyOf: 'Bm',
    songAndChords:
`
[Intro]
Em     D/F# G      D      C
 
[Verse 1]
Em                  D/F#    G
   You call me out upon the waters
           D                  C
The great unknown where feet may fail
Em                      D/F#   G
   And there I find you in the mystery
      D                   C
In oceans deep, my faith will stand
 
[Chorus]
C            G          D
  And I will call upon Your name
C             G           D
  And keep my eyes above the waves
            C                 G             D
When oceans rise my soul will rest in Your embrace
         C         D    Em      D/F# G     D     C
For I am Yours and You are mine
 
[Verse 2]
Em                       D/F#    G
   Your grace abounds in deepest waters
           D                 C
Your sovereign hand will be my guide
Em                         D/F#    G
   Where feet may fail and fear surrounds me
          D                         C
You’ve never failed and You won’t start now
 
[Chorus]
C           G          D
  So I will call upon Your name
C             G           D
  And keep my eyes above the waves
            C                 G             D
When oceans rise my soul will rest in Your embrace
         C         D    Em       D/F# G     D     C
For I am Yours and You are mine, oh
          Em      D/F# G     D     C
And You are mine, oh
 
[Bridge]
Em     C     G     D     x2
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
C                          G
  Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
C                         G
  Take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
Em                 D/F#     G
   Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
Em                 D/F#    G
   Take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
Em                 D/F#     G
   Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
Em                     D/F#    G
   And take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
[Instrumental]
Em     D/F# G      D      Am      x2
 
[Chorus]
C        G            D
  I will call upon Your name
C         G           D
  Keep my eyes above the waves
C              G             D
  My soul will rest in Your embrace
     C         D    Em
I am Yours and You are mine
`
},
{

    id: 3,
    title: 'Mahal na mahal kita Panginoon',
    keyOf: 'D',
    songAndChords:
`

[Verse]
D              G            D G A
Mahal na mahal kita Panginoon
D              G            A
Mahal na mahal kita Panginoon
      G               F#m
Kailanmay di kita ipagpapalit
   G             F#m
Pagkat sa piling mo’y langit
Em       F#m     A         D
Mahal na mahal kita Panginoon
 
 
[Chorus]
      F#m Bm  Em        A
Habangbuhay papupurihan ka
      F#m Bm   Em            A
Habangbuhay maglilingkod say o
      F#m Bm  Em                  A
Habangbuhay pag-ibig ko say’oy iaalay
 
(Repeat)
`
},
{
    id: 4,
    title: 'Lord I offer my Life.',
    keyOf: 'E',
    songAndChords:
    `
[Verse 1]
 
E               F#m
All that I am, all that I have,
B                      A        E
I lay them down before You, O Lord.
C#m             A
All my regrets, all my acclaim,
F#m             E      A              F#m  B
The joy and the pain, I'm making them Yours.
 
[Verse 2]
 
E                   F#m
Things in the past, things yet unseen,
B                          A           E
Wishes and dreams that are yet to come true.
C#m              A
All of my hopes, all of my plans,
F#m             E         A         F#m  B
My heart and my hands are lifted to you.
 
 
[Chorus]
 
 E                 C#m
Lord, I offer my life to You.
           F#m              E      A               B
Everything I've been through, use it for Your Glory.
 E               C#m
Lord, I offer my days to You,
             F#m       E    A            G#m    C#m
Lifting my praise to You, as a pleasing sacrifice
 F#m        A   B      E
Lord, I offer You my life.
 
 
[Verse 1]
 
E               F#m
All that I am, all that I have,
B                      A        E
I lay them down before You, O Lord.
C#m             A
All my regrets, all my acclaim,
F#m             E      A              F#m  B
The joy and the pain, I'm making them Yours.
 
 
[Verse 2]
 
E                   F#m
Things in the past, things yet unseen,
B                           A           E
Wishes and dreams that are yet to come true,
C#m               A
All of my hopes, all of my plans,
F#m             E          A        F#m  B
My heart and my hands are lifted to You.
 
 
[Chorus]
 
 E                 C#m
Lord, I offer my life to You.
           F#m              E      A               B
Everything I've been through, use it for Your Glory.
 E               C#m
Lord, I offer my days to You,
             F#m       E    A            G#m    C#m
Lifting my praise to You, as a pleasing sacrifice
 F#m        A   B      E
Lord, I offer You my-
 
 
[End]
 
 E                 C#m
Lord, I offer my life to You.
           F#m              E      A               B
Everything I've been through, use it for Your Glory.
 E               C#m
Lord, I offer my days to You,
             F#m       E    A            G#m    C#m
Lifting my praise to You, as a pleasing sacrifice
 F#m     A    B      E
Lord, I offer You my life
 
 F#m     A    B      E
Lord, I offer You my life
    `
},
{
    id: 5,
    title: 'May galak, may saya, may tuwa',
    keyOf: 'D',
    songAndChords:
`
     D          G      F#m
May galak, may saya, may tuwa
                  G
Sa piling ng Diyos
          D         G          Em           A
Sapagkat hirap ng puso ay naglalaho
         D           G          F#m
May awit, may sayaw, at papuri
           G
Para sa Diyos
        D               G        Em              A  - A break
Na hatid ng pusong pinagpala Niyang lubos
 
 
[Chorus]
 
           G        A
Handog N'ya ay kapayapaan
           F#m      Bm
Handog N'ya ay kagalakan
           Em       A
Handog N'ya ay kalakasan
               D             D7
Sa bawat pusong napapagal
               G         A
Kaya't ang awit ng papuri
       F#m         Bm
Awit ng pasasalamat
       Em          A - A break
At ang awit ng pagsamba
                      (D)
Ay para lang sa Kanya

  end...

Bb       C          D
   Ay para lang sa Kanya
Bb       C          D
   Ay para lang sa Kanya
Bb       C          D
   Ay para lang sa Kanya 
`
},
{
    id: 6,
    title: '10,000 Reasons',
    keyOf: 'G',
    songAndChords:
`
[Intro]
C G D/F# Em
C G Dsus4 D
 
[Chorus]
          C          G
Bless the Lord, O my soul,
D/F# Em
O my soul,
C             G    Dsus4 D
Worship His holy name.
          C        Em
Sing like never before,
C D  Em
O my soul.
     C              D        C/G  G
I'll worship Your holy name.
 
[Verse 1]
    C         G           D       Em
The sun comes up, it's a new day dawning;
C            G            D     Em
It's time to sing Your song again.
C            G              D           Em
Whatever may pass, and whatever lies before me,
C2         G                Dsus4 D  G   Gsus4 G
Let me be singing when the even- ing comes.
 
[Chorus]
           C          G
Bless the Lord, O my soul,
D/F# Em
O my soul,
C             G    Dsus4 D
Worship His holy name.
          C        Em
Sing like never before,
C D  Em
O my soul.
     C              D        C/G  G
I'll worship Your holy name.
 
[Verse 2]
       C       G                D        Em
You're rich in love, and You're slow to anger.
      C       G               D         Em
Your name is great, and Your heart is kind.
    C        G                D       Em
For all Your goodness, I will keep on singing;
C2           G              Dsus4 D  G    Gsus4 G
Ten thousand reasons for my heart to find.
 
[Chorus]
           C          G
Bless the Lord, O my soul,
D/F# Em
O my soul,
C             G    Dsus4 D
Worship His holy name.
          C        Em
Sing like never before,
C D  Em
O my soul.
     C              D        C/G  G
I'll worship Your holy name.
 
[Verse 3]
    C       G           D            Em
And on that day when my strength is failing,
    C         G            D         Em
The end draws near, and my time has come;
C        G                   D        Em
Still my soul will sing Your praise unending:
C2           G                 Dsus4  D  G  Gsus4 G
Ten thousand years and then fore - - vermore!
 
[Chorus] (x2)
           C          G
Bless the Lord, O my soul,
D/F# Em
O my soul,
C             G    Dsus4 D
Worship His holy name.
          C        Em
Sing like never before,
C D  Em
O my soul.
     C             D     G
I'll worship Your holy name.
 
[Ending]
            C             D     Em
Yes, I will worship Your holy name.
           C             D     G
Lord, I'll worship Your holy name.
`
},
{
    id: 7,
    title: 'Shout to the Lord',
    keyOf: 'G',
    songAndChords:
`
[Verse]
 
G         D           Em            D         C
 My Jesus, My Savior, Lord there is none like you
           G                Em                        F   F6 C
All of my days, I want to praise, the wonders of your mighty love
G           D            Em        D            C
 My comfort, My shelter, tower of refuge and strength
            G                Em                 F  C/E  Dsus4 D
Let every breath, all that I am, never cease to worship you
 
 
[Chorus]
 
G             Em           C           D
Shout to the Lord all the earth let us sing
G         Em       C             D
Power and majesty praise to the king
Em                          C                    D     C/D     D
Mountains bow down and the seas will roar at the sound of your name
G           Em        C             D
I sing for joy at the work of your hands
G             Em         C           D
Forever I'll love you forever I'll stand
Em                        C                G
Nothing compares to the promise I have in You
`
},
{
    id: 8,
    title: 'Give thanks',
    keyOf: 'D',
    songAndChords:
`

[Intro]
D F#m A Bm G
 
 
[Verse]
D           A
Give thanks with a grateful heart
Bm          D  F#m      A
Give thanks to the Holy One
G           D                  C             A
Give thanks because He's given Jesus Christ, His Son
 
 
[Chorus]
F#m     A       Bm   Em   D  Em
And now let the weak say, "I am strong"
Em           A     D A   D
Let the poor say, "I am rich
F#m        Bm   A   Bm       C        D   A
Because of what the Lord has done for us" [x2]
D
Give thanks
 
 
[Verse]
D           A
Give thanks with a grateful heart
Bm          D  F#m      A
Give thanks to the Holy One
G           D                  C             A
Give thanks because He's given Jesus Christ, His Son
 
 
[Chorus]
F#m     A       D    A         D  Em
And now let the weak say, "I am strong"
A            D     A   D
Let the poor say, "I am rich
F#m        Bm   C            D    A
Because of what the Lord has done for us" [x2]
D
Give thanks
`
},
{
    id: 9,
    title: 'Masiglang umawit',
    keyOf: 'D',
    songAndChords:
`
[Intro]
D  Bm  Em  A
F#m Bm C A
 
[Verse]
      D      Bm     Em          A
Masiglang umawit sa saliw ng tugtugan
 
    D        Bm        Em         A
Umindak, sumayaw, at tayo’y maglundagan
 
   D        Bm         Em       A
Siya’y sambahin nang buong kalakasan
 
 D       Bm          Em         A
Ating isigaw ang Kanyang kabutihan
 
 
[Chorus]
 
G           F#m
Sa lahat ng oras
 
G          F#m
Siya’y maasahan
 
G            F#m  Bm    C          A
Ang pag-ibig Niya ay laging nananahan
 
G         F#m     G             F#m
Mga puso natin ay pinupuno ng kaligayahan
 
G            F#m    Bm         C          A
Kaya’t dapat ipagdiwang ang Kanyang kabutihan
`
}
];

localStorage.setItem('lists', JSON.stringify(churchSongs));
console.log(churchSongs);
