export const churchSongs = [
{
    id: 1,
    title: 'To my knees',
    keyOf: 'C',
    songAndChords:
    `
[Intro]
 
C | F | Am G C/E | F |
 
 
[Verse 1]
 
       C
In the Saviour's love
       F
I find joy beyond compare
        Am           G   C/E  F
Endless peace covers all of   me
         C
When You breathe within
         F
You turn winter into spring
         Am            G   C/E  F
Grace dissolves every fear in   me
 
 
[Chorus]
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
 
[Instrumental]
 
C | F | Am G C/E | F |
 
 
[Verse 2]
 
      C
In my vacant heart
         F
Lord You came and made a home
          Am           G    C/E  F
You bring light to the dark in   me
       C
When I lose my way
     F
I am beckoned into grace
     Am          G   C/E    F
You alone are my e - very - thing
 
 
[Chorus] x2
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C |
 
 
[Bridge] x2
 
G                       Dm          F    C
  All the earth sing of mercy never en - ding
G                     Dm              F   C
  I will worship with all that is within me
G            Dm          F  C
  Holy holy, Lord God almighty
G                  Dm          F  C
  King of heaven, Yours is the glory
 
| G |
 
 
[Chorus]
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C |
 
 
[Instrumental] x10
 
| C  Dm | Am  G | F | C  G |
 
 
[Chorus] x2
 
C                   Dm    Am
Your love brings me to my knees
          G       F
Brings me to my knees
   C       G
My King forever
C              Dm      Am
You are all my heart desires
          G     F
Until the end of time
    C      G
My soul surrendered
 
| C

`
},
{
    id: 2,
    title: 'Oceans',
    keyOf: 'Bm',
    songAndChords:
`
[Intro]
Em     D/F# G      D      C
 
[Verse 1]
Em                  D/F#    G
   You call me out upon the waters
           D                  C
The great unknown where feet may fail
Em                      D/F#   G
   And there I find you in the mystery
      D                   C
In oceans deep, my faith will stand
 
[Chorus]
C            G          D
  And I will call upon Your name
C             G           D
  And keep my eyes above the waves
            C                 G             D
When oceans rise my soul will rest in Your embrace
         C         D    Em      D/F# G     D     C
For I am Yours and You are mine
 
[Verse 2]
Em                       D/F#    G
   Your grace abounds in deepest waters
           D                 C
Your sovereign hand will be my guide
Em                         D/F#    G
   Where feet may fail and fear surrounds me
          D                         C
You’ve never failed and You won’t start now
 
[Chorus]
C           G          D
  So I will call upon Your name
C             G           D
  And keep my eyes above the waves
            C                 G             D
When oceans rise my soul will rest in Your embrace
         C         D    Em       D/F# G     D     C
For I am Yours and You are mine, oh
          Em      D/F# G     D     C
And You are mine, oh
 
[Bridge]
Em     C     G     D     x2
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
Em                          C
   Spirit lead me where my trust is without borders
        G                      D
Let me walk upon the water wherever You would call me
Em                         C
   Take me deeper than my feet could ever wander
        G                                  D
And my faith will be made stronger in the presence of my Savior
 
C                          G
  Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
C                         G
  Take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
Em                 D/F#     G
   Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
Em                 D/F#    G
   Take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
Em                 D/F#     G
   Spirit lead me where my trust is without borders
        D                      Am
Let me walk upon the water wherever You would call me
Em                     D/F#    G
   And take me deeper than my feet could ever wander
        D                                  Am
And my faith will be made stronger in the presence of my Savior
 
[Instrumental]
Em     D/F# G      D      Am      x2
 
[Chorus]
C        G            D
  I will call upon Your name
C         G           D
  Keep my eyes above the waves
C              G             D
  My soul will rest in Your embrace
     C         D    Em
I am Yours and You are mine
`
},
{

    id: 3,
    title: 'Mahal na mahal kita Panginoon',
    keyOf: 'D',
    songAndChords:
`

[Verse]
D              G            D G A
Mahal na mahal kita Panginoon
D              G            A
Mahal na mahal kita Panginoon
      G               F#m
Kailanmay di kita ipagpapalit
   G             F#m
Pagkat sa piling mo’y langit
Em       F#m     A         D
Mahal na mahal kita Panginoon
 
 
[Chorus]
      F#m Bm  Em        A
Habangbuhay papupurihan ka
      F#m Bm   Em            A
Habangbuhay maglilingkod say o
      F#m Bm  Em                  A
Habangbuhay pag-ibig ko say’oy iaalay
 
(Repeat)
`
},
];

localStorage.setItem('lists', JSON.stringify(churchSongs));
console.log(churchSongs);
